name: Build/Test for PR and collaborator push

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'CHANGELOG.rst'
  push:
    paths-ignore:
      - 'doc/**'
      - 'CHANGELOG.rst'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ubuntu_versions : [
          20.04,
          22.04,
          24.04,
        ]
        pkg_mgr : [
          apt,
          conda,
        ]
        cyclus_tag: [
          latest,
          stable,
        ]
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Checkout Areal
        uses: actions/checkout@v4

      - name: Build and test Areal
        id: build-areal
        continue-on-error: true
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile
          cache-from: type=registry,ref=ghcr.io/cyclus/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cyclus:ci-layer-cache
          tags: localhost:5000/cyclus:local
          push: true
          build-args: |
            pkg_mgr=${{ matrix.pkg_mgr }}
            ubuntu_version=${{ matrix.ubuntu_versions }}
            cyclus_tag=ci-layer-cache

      - name: Export Environment Variables
        if: github.event_name == 'pull_request'
        run: |
          echo "AREAL_BUILD_STATUS=${{steps.build-areal.outcome == 'success' && '**Success** :white_check_mark:' || 
          steps.build-areal.outcome == 'failure' && '**Failure** :x:' || 
          '**Skipped due to upstream failure** :warning:'}}" >> "$GITHUB_ENV"

          echo "ARTIFACT_NAME=${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}_${{ matrix.cyclus_tag }}" >> "$GITHUB_ENV"

      - name: Construct Artifact
        if: github.event_name == 'pull_request'
        run: |
          echo "
          ##### Build \`FROM cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cyclus:${{ matrix.cyclus_tag }}\`
           - Areal: ${{ env.AREAL_BUILD_STATUS }}" > ${{ env.ARTIFACT_NAME }}.txt
      
      - name: Upload Artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}.txt

  upload-pr-number:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Areal
        uses: actions/checkout@v4

      - name: Save PR number to file
        run: |
          echo "${{ github.event.number }}" > pr_number
          echo "${{ github.event.pull_request.head.sha }} - $(git log -1 --format=%ci)" > commit_hash_timestamp
      
      - name: Upload PR number artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr_number

      - name: Upload Commit hash artifact
        uses: actions/upload-artifact@v4
        with:
          name: commit_hash_timestamp
          path: commit_hash_timestamp